# 这些是 GitHub 赞助按钮的支持方式
# 取消注释你想启用的方式

# github: [Jayaway]  # GitHub Sponsors
# patreon: # Patreon
# open_collective: # Open Collective
# ko_fi: # Ko-fi
# tidelift: # Tidelift
# community_bridge: # Community Bridge
# liberapay: # Liberapay
# issuehunt: # IssueHunt
# otechie: # Otechie
# custom: # 自定义链接
